### ISSUE TITLE
screen-256color

### ISSUE THREAD

**Issue by carlosdcastillo** [asottile/babi#59]
The following don't work under tmux with

set -g default-terminal "screen-256color"

in the ~/.tmux.conf

(I heard on your stream that you dislike tmux, still babi should work on tmux)

these do not work:

shift-left, shift-right, shift-up, shift-down, in fact any selection key combination

these also don't work:

alt-left, alt-right, ctrl-left, ctrl-right

these do work:

tab and shift-tab work

colors, highlighting, everything else works. pretty usable.

**Comment by asottile** [comment]
that's odd, I use `tmux` to test `babi` so it should work -- is it possibly your configuration that's interfering?

**Comment by asottile** [comment]
I just tried each of those keys and they work in my terminal emulator (~basically stock `gnome-terminal`) with tmux, here's [my tmux config](https://github.com/asottile/scratch/blob/master/.tmux.conf)

**Comment by carlosdcastillo** [comment]
Strange. It didn't work with your config either. I use st. Without tmux babi works works fine on st.

**Comment by asottile** [comment]
very weird indeed, seems to work for me:

![](https://i.fluffy.cc/nmvnrHv8NzSw9Z8t2jTwsl1fcvJ6njmL.png)

I compiled st 0.8.2 from source

the only weird part was attempting to open tmux:

```console
$ tmux
open terminal failed: missing or unsuitable terminal: st-256color
```

but was able to get it working with

```console
$ TERM=xterm-256color tmux
```

my guess (?) is that `tmux` itself has problems with `TERM=st-256color`

**Comment by nicm** [comment]
Modifiers and arrow keys are a pain and not always reliable. Most likely is one of:

- st doesn't send xterm-style arrow keys and it doesn't have `kUP6`, `kUP4` etc in `st-256color` so tmux can recognise what it does send. This is perhaps unlikely since st is relatively new. But try `xterm-256color` instead outside tmux?

- This is an old tmux version with the `xterm-keys` option turned off and the application expects xterm-style arrow keys. Possible? Add `set -g xterm-keys on` to `.tmux.conf`.

- The application looks at `kUP4`, `kUP6` etc but these are not present with `screen-256color`. It looks like this is not the case. If it were, you can use `tmux-256color` inside tmux instead.

**Comment by carlosdcastillo** [comment]
Yes, I am using tmux 2.3 which is kind of old. After doing set -g xterm-keys on, babi started working inside tmux. Very nice. Thank you very much!

**Comment by asottile** [comment]
🎉  glad we could get to the bottom of this
